//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZipArc.rc
//
#define IDD_GETFROM                     1
#define IDS_ADDFOLDER                   100
#define IDS_ARCHINFO                    101
#define IDS_COL1                        0x66
#define IDS_COL2                        0x67
#define IDS_COL3                        0x68
#define IDS_COL4                        0x69
#define IDS_COL5                        0x6A
#define IDS_COL6                        0x6B
#define IDS_ARICR                       108
#define IDS_ARIDS                       109
#define IDS_ARIEX                       110
#define IDS_PRCOMPRESS                  0x6F
#define IDS_PREXTRACT                   0x70
#define IDS_ARINORMAL                   113
#define IDS_PRTEST                      0x72
#define IDS_ASSOCEXISTS                 115
#define IDS_CANNOTCLOSE                 116
#define IDS_CANTINTERRUPT               117
#define IDS_CHGDSK                      118
#define IDS_CHGEX                       119
#define IDS_CHGNOTCR                    120
#define IDS_PRDELETE                    0x79
#define IDS_CHGSPACE                    122
#define IDS_CHGWRPR                     123
#define IDS_COMMAND                     124
#define IDS_COMPREFF                    125
#define IDS_COMPREXTR                   126
#define IDS_COMPRINEFF                  127
#define IDR_MAINFRAME                   128
#define IDR_ZIPARCTYPE                  129
#define IDS_COMPRINFO                   130
#define IDS_DIR                         131
#define IDS_DUPLICATED                  132
#define IDS_ERR                         133
#define IDS_ERRINFILE                   134
#define IDS_EXISTS                      135
#define IDS_EXTRACTTO                   136
#define IDS_FIDISPCOMM                  137
#define IDS_FIDISPINFO                  138
#define IDS_METH0                       0x8B
#define IDS_METH1                       0x8C
#define IDS_METH2                       0x8D
#define IDS_METH3                       0x8E
#define IDS_METH4                       0x8F
#define IDS_METH5                       0x90
#define IDS_METH6                       0x91
#define IDS_METH7                       0x92
#define IDS_METH8                       0x93
#define IDS_METH9                       0x94
#define IDS_METH10                      0x95
#define IDS_FILE                        150
#define IDS_FILE_SAVE                   151
#define IDS_FILEINFO                    152
#define IDS_FINALIZE                    153
#define IDS_FINISHED                    154
#define IDS_FINNO                       155
#define IDS_FINOK                       156
#define IDS_FROM                        157
#define IDS_INFCOMM                     158
#define IDS_INFINF                      159
#define IDS_INFOARCH                    160
#define IDS_INFOFILE                    161
#define IDS_INFOMFCOM                   162
#define IDS_MAKING_SPACE                163
#define IDS_MODIFYING                   164
#define IDS_NO                          165
#define IDS_NOGLOBAL                    166
#define IDS_NOTHING                     167
#define IDS_NOTREG                      168
#define IDS_NOTREMOVED                  169
#define IDS_NOTSUCCESS                  170
#define IDS_OPENFAILED                  171
#define IDS_PAGE1                       172
#define IDS_PAGE2                       173
#define IDS_PAGE3                       174
#define IDS_PAGE4                       175
#define IDS_PAGE5                       176
#define IDS_PASSNOTMATCH                177
#define IDS_PATTERN                     178
#define IDS_RENAMING                    179
#define IDS_REPLACE_PROMPT              180
#define IDS_PANE_INFO1                  0xB5
#define IDS_PANE_INFO2                  0xB6
#define IDS_PANE_INFO3                  0xB7
#define IDS_PANE_INFO4                  0xB8
#define IDS_PANE_INFO5                  0xB9
#define IDS_REPLACE_PROMPT_SPAN         186
#define IDS_REPORT                      187
#define IDS_SAFEABORT                   188
#define IDS_SAVETITLE                   189
#define IDS_SAVNOTSAFE                  190
#define IDS_SELECTTEMP                  191
#define IDS_TO                          192
#define IDS_UNKNOWN                     193
#define IDS_UNREG                       194
#define IDS_YES                         195
#define IDS_NOCDONREMOV                 196
#define IDS_NO_ZIP_TO_GET_FROM          197
#define IDS_GETFROM_PROMPT              198
#define IDS_GETTING_FROM_ARCHIVE        199
#define IDD_SAVEMODIFIED                500
#define IDI_MODIFIED                    501
#define IDI_REPORT                      502
#define IDP_OLE_INIT_FAILED             504
#define IDD_NEW                         507
#define IDD_PASSWORD                    508
#define IDD_EXTRACT                     509
#define IDD_FILEINFO                    510
#define IDR_COMMAND_ACTION              511
#define IDR_COMMAND_STOP                512
#define IDD_REPORT                      513
#define IDI_READONLY                    514
#define IDI_EXCEPT                      515
#define IDD_OPTCOMPR                    517
#define IDD_OPTGENRAL                   518
#define IDD_OPTABOUT                    519
#define IDD_OPTAPPEAR                   520
#define IDD_CONTAINER                   522
#define IDI_MULTIDISK                   527
#define IDC_MOVE                        529
#define IDD_OPTSMART                    530
#define IDD_SAPREFS                     532
#define IDD_SELECT                      534
#define IDD_REPLACE                     535
#define IDC_SMART                       1001
#define IDC_VOL                         1002
#define IDC_LEVEL                       1003
#define IDC_PASS                        1005
#define IDC_CONF                        1006
#define IDC_COMMENT                     1007
#define IDC_FILENAME                    1008
#define IDC_TEMPBROWSE                  1011
#define IDC_EXTRACT                     1012
#define IDC_EXFULLPATH                  1013
#define IDC_INF                         1014
#define IDC_CHGDSP                      1015
#define IDC_CLEAR                       1016
#define IDC_ASSOCIATE                   1017
#define IDC_RECURSIVE                   1018
#define IDC_ASSUMETD                    1019
#define IDC_SORTED                      1020
#define IDC_MAXIMIZED                   1021
#define IDC_BROWSE                      1023
#define IDC_ALWAYS                      1024
#define IDC_PKSPAN                      1025
#define IDC_QUESTION                    1026
#define IDC_DISPLAYING                  1028
#define IDC_TDSPAN                      1029
#define IDC_CLPASS                      1032
#define IDC_STORESMALL                  1033
#define IDC_SETDEFAULT                  1037
#define IDC_SMARTOPT                    1044
#define IDC_SPANNING                    1045
#define IDC_INFOBUTTON                  1049
#define IDC_OVERWRITE                   1050
#define IDC_FRAME                       1056
#define IDC_DEFAULT                     1057
#define IDC_DLG_FRAME                   1058
#define IDC_SYSTCOMP                    1059
#define IDC_USETEMP                     1060
#define IDC_FILENAMES                   1060
#define IDC_CAPTION_BAR                 1061
#define IDC_TEMPPATH                    1062
#define IDC_PAGE_TREE                   1063
#define IDC_STATICVOL                   1064
#define IDC_EXALL                       1065
#define IDC_EXSEL                       1066
#define IDC_PATTERN                     1067
#define IDC_CS                          1069
#define IDC_FILENAMEONLY                1070
#define IDC_REPLACE                     1073
#define IDC_DONT_ASK                    1078
#define IDC_ICON_Q                      1079
#define IDC_PROMPT                      1084
#define IDC_REPLACE_ACTION              1086
#define IDC_PROMPT_GET_FROM_ARCH        1087
#define IDC_GET_FROM                    1088
#define IDC_RADIO_STD                   1089
#define IDC_RADIO_AES128                1090
#define IDC_RADIO_AES192                1091
#define IDC_RADIO_AES130                1092
#define IDC_RADIO_AES256                1092
#define ID_FILE_SETPRIORITY_IDLE        0x800F
#define ID_FILE_SETPRIORITY_LOWEST      0x8010
#define ID_FILE_SETPRIORITY_BELOWNORMAL 0x8011
#define ID_FILE_SETPRIORITY_NORMAL      0x8012
#define ID_FILE_SETPRIORITY_ABOVENORMAL 0x8013
#define ID_FILE_SETPRIORITY_HIGHEST     0x8014
#define ID_FILE_SETPRIORITY_TIMECRITICAL 0x8015
#define ID_COMMAND_ABORT                35000
#define ID_COMMAND_ADD_FILES            35001
#define ID_COMMAND_ADD_FOLDERS          35002
#define ID_COMMAND_COMMENT_FILE         35003
#define ID_COMMAND_COMMENT_GLOBAL       35004
#define ID_COMMAND_DELETE_SELECTED      35005
#define ID_COMMAND_EXTRACT              35006
#define ID_COMMAND_PASTEFILES           35007
#define ID_COMMAND_RENAME               35008
#define ID_COMMAND_SEARCHSELECT         35009
#define ID_COMMAND_SETPASSWORD          35010
#define ID_COMMAND_STOP                 35011
#define ID_COMMAND_TEST_SELECTED        35012
#define ID_FILE_FINALIZE                35013
#define ID_FILE_INFORMATION             35014
#define ID_FILE_OPTIONS                 35015
#define ID_GETFROMARCHIVE               35016
#define ID_HELP_WEBHOMEPAGE             35017
#define ID_INDICATOR_SEL                35018
#define ID_RENAME                       35019
#define ID_SELECTALL                    35020
#define ID_STATICCHECKBOX               35021
#define ID_VIEW_FILEINFO                35022
#define ID_VIEW_REFRESH                 35023
#define ID_VIEW_REPORT                  35024
#define ID_COMMAND_GETFROMARCHIVE       35026
#define IDS_COUNTING                    0xE00C
#define IDS_PRCOMPRESSMOVE              0xE00E
#define IDS_PRCOMPRESSSTORE             0xE00F
#define IDS_PRDELCHECK                  0xE010
#define IDS_PRSAVING                    0xE011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        4
#define _APS_NEXT_COMMAND_VALUE         35027
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           57462
#endif
#endif
